/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.editor.item;

import com.alex.loaders.items.ItemDefinitions;
import com.editor.Main;
import com.editor.Utils;
import javafx.scene.control.Labeled;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.util.HashMap;

import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Travis
 */
public class ItemEditor extends javax.swing.JFrame {

    private ItemDefinitions defs;
    private ItemSelection is;
	private JLabel oldInvModel;
	private JLabel oldMaleEquipModelId3;
	private JLabel oldFemaleEquipModelId3;
	private JLabel oldMaleEquipModelId2;
	private JLabel oldFemaleEquipModelId2;
	private JLabel oldMaleEquipModelId1;
	private JLabel oldFemaleEquipModelId1;
	private javax.swing.JCheckBox aBool125;
	private JLabel anInt60;
	private javax.swing.JCheckBox aBool130;
    private javax.swing.JTextField unnotedId;
    private javax.swing.JTextField notedId;
    private  javax.swing.JTextField placeHolderId;
    private  javax.swing.JTextField placeHolderTemplateId;
    private javax.swing.JTextField shiftClickIndex;
    private  javax.swing.JTextField category;
    /**
     * Creates new form ItemEditor
     */
    public ItemEditor(ItemSelection is, ItemDefinitions defs) {
        this.defs = defs;
        this.is = is;
        initComponents();
        setResizable(false);
        setTitle("Item Editor");
        setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        itemName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        value = new javax.swing.JTextField();
        teamId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        membersOnly = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        equipSlot = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        equipType = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        stackIDs = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        stackAmts = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        stackable = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        switchNote = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        note = new javax.swing.JTextField();
        searchable = new javax.swing.JCheckBox();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        switchLend = new javax.swing.JTextField();
        lend = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        invModelZoom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        modelRot1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ModelRot2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ModelOffset1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        modelOffset2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        invModel = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        maleEquip1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        femaleEquip1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        maleEquip2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        femaleEquip2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        maleEquip3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        femaleEquip3 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        invOptions = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        groundOptions = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        modelColors = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        textureColors = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        array1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        array2 = new javax.swing.JTextField();
        array3 = new javax.swing.JTextField();
        array4 = new javax.swing.JTextField();
        array5 = new javax.swing.JTextField();
        array6 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        int1 = new javax.swing.JTextField();
        int2 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        int3 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        int4 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        int5 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        int6 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        int7 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        int8 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        int9 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        int10 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        int11 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        int12 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        int13 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        int14 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        int15 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        int16 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        int17 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        int18 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        int19 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        int20 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        int21 = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        int22 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        int23 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientScriptOutput = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        csk1 = new javax.swing.JTextField();
        csk2 = new javax.swing.JTextField();
        csk3 = new javax.swing.JTextField();
        csk4 = new javax.swing.JTextField();
        csk5 = new javax.swing.JTextField();
        csk6 = new javax.swing.JTextField();
        csk7 = new javax.swing.JTextField();
        csv1 = new javax.swing.JTextField();
        csv2 = new javax.swing.JTextField();
        csv3 = new javax.swing.JTextField();
        csv4 = new javax.swing.JTextField();
        csv5 = new javax.swing.JTextField();
        csv6 = new javax.swing.JTextField();
        csv7 = new javax.swing.JTextField();
        currentViewLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        reloadMenuBtn = new javax.swing.JMenuItem();
        saveMenuBtn = new javax.swing.JMenuItem();
        addModelMenuBtn = new javax.swing.JMenuItem();
        exportMenuBtn = new javax.swing.JMenuItem();
        exitMenuBtn = new javax.swing.JMenuItem();
        int24 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name");

        itemName.setText(""+defs.getName());

        jLabel2.setText("Value");

        value.setText(""+defs.getValue());

        teamId.setText(""+defs.getTeam());

        jLabel3.setText("Team");

        membersOnly.setSelected(defs.isMembersObject());
        membersOnly.setText("Members Only");

        jLabel20.setText("Equip Slot");

        equipSlot.setText(""+defs.getEquipSlot());

        jLabel21.setText("Equip Type");

        equipType.setText(""+defs.getEquipType());

        jLabel22.setText("Stack IDs");

        stackIDs.setText(getStackIDs());

        jLabel23.setText("Stack Amounts");

        stackAmts.setText(getStackAmts());

        jLabel24.setText("Stackable");

        stackable.setText(""+defs.getStackable());

        jLabel58.setText("Switch Note Item ID");

        switchNote.setText(""+defs.certID);

        jLabel59.setText("Noted Item ID");

        note.setText(""+defs.certTemplateID);

        searchable.setSelected(defs.isSearchable());
        searchable.setText("Unnoted");

        jLabel60.setText("Switch Lend Item ID");

        jLabel61.setText("Lent Item ID");

        switchLend.setText(""+defs.getunNotedID());

        lend.setText(""+defs.getLendedItemId());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchable)
                    .addComponent(membersOnly)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(equipSlot, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(itemName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(teamId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(value, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stackable, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(126, 126, 126)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stackAmts, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stackIDs, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(equipType, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel58)
                            .addComponent(jLabel59))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(switchNote, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(note))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel60)
                            .addComponent(jLabel61))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(switchLend, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(lend))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(itemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(stackIDs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teamId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stackAmts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(stackable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(membersOnly)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(equipSlot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(equipType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel58)
                    .addComponent(switchNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel60)
                    .addComponent(switchLend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel59)
                    .addComponent(note, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel61)
                    .addComponent(lend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchable)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("General", jPanel1);

        jLabel4.setText("Inventory Model Zoom");

        invModelZoom.setText(""+defs.getSpriteScale());

        jLabel5.setText("Model Rotation 1");

        modelRot1.setText(""+defs.getSpritePitch());

        jLabel6.setText("Model Rotation 2");

        ModelRot2.setText(""+defs.getSpriteCameraRoll());

        jLabel7.setText("Model Offset 1");

        ModelOffset1.setText(""+defs.getSpriteTranslateX());

        jLabel8.setText("Model Offset 2");

        modelOffset2.setText(""+defs.getSpriteTranslateY());

        jLabel9.setText("Inventory Model");

        invModel.setText(""+defs.getModelId());

        jLabel10.setText("Male Equip 1");

        maleEquip1.setText(""+defs.getPrimaryMaleModel());

        jLabel11.setText("Female Equip 1");

        femaleEquip1.setText(""+defs.getPrimaryFemaleModel());

        jLabel12.setText("Male Equip 2");

        maleEquip2.setText(""+defs.getSecondaryMaleModel());

        jLabel13.setText("Female Equip 2");

        femaleEquip2.setText(""+defs.getSecondaryFemaleModel());

        jLabel14.setText("Male Equip 3");

        maleEquip3.setText(""+defs.getTertiaryMaleEquipmentModel());

        jLabel15.setText("Female Equip 3");

        femaleEquip3.setText(""+defs.getTertiaryFemaleEquipmentModel());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ModelOffset1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ModelRot2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modelRot1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(invModelZoom, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modelOffset2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(114, 114, 114)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(femaleEquip3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maleEquip1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(invModel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maleEquip2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(femaleEquip1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(maleEquip3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(femaleEquip2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(invModelZoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(invModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(modelRot1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(maleEquip1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ModelRot2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(femaleEquip1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(ModelOffset1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(modelOffset2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(femaleEquip2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maleEquip2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(maleEquip3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(femaleEquip3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Model", jPanel2);

        jLabel16.setText("Inventory Options");

        invOptions.setText(getInventoryOpts());

        jLabel17.setText("Ground Options");

        groundOptions.setText(getGroundOpts());

        jLabel18.setText("Model Colors");

        modelColors.setText(getChangedModelColors());

        jLabel19.setText("Texture Colors");

        textureColors.setText(getChangedTextureColors());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(invOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(groundOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(modelColors, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(textureColors, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(312, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(groundOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modelColors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textureColors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Options", jPanel3);

        jLabel25.setText("unknownArray1");

        array1.setText(getUnknownArray1());

        jLabel27.setText("unknownArray2");

        jLabel28.setText("unknownArray3");

        jLabel29.setText("unknownArray4");

        jLabel30.setText("unknownArray5");

        jLabel31.setText("unknownArray6");

        array2.setText(getUnknownArray2());

        array3.setText(getUnknownArray3());

        array4.setText(getUnknownArray4());

        array5.setText(getUnknownArray5());

        array6.setText(getUnknownArray6());

        jLabel32.setText("unknownInt1");

        int1.setText(""+defs.primaryMaleHeadPiece);

        int2.setText(""+defs.primaryFemaleHeadPiece);

        jLabel33.setText("unknownInt2");

        jLabel34.setText("unknownInt3");

        int3.setText(""+defs.secondaryMaleHeadPiece);

        jLabel35.setText("unknownInt4");

        int4.setText(""+defs.secondaryFemaleHeadPiece);

        jLabel36.setText("unknownInt5");

        int5.setText(""+defs.spriteCameraYaw);

        jLabel37.setText("unknownInt6");

        int6.setText(""+defs.unknownInt6);

        jLabel38.setText("unknownInt7");

        int7.setText(""+defs.groundScaleX);

        jLabel39.setText("unknownInt8");

        int8.setText(""+defs.groundScaleY);

        jLabel40.setText("unknownInt9");

        int9.setText(""+defs.groundScaleZ);

        jLabel41.setText("unknownInt10");

        int10.setText(""+defs.ambience);

        jLabel42.setText("unknownInt11");

        int11.setText(""+defs.diffusion);

        jLabel43.setText("unknownInt12");

        int12.setText(""+defs.unknownInt12);

        jLabel44.setText("unknownInt13");

        int13.setText(""+defs.unknownInt13);

        jLabel45.setText("unknownInt14");

        int14.setText(""+defs.unknownInt14);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34)
                            .addComponent(jLabel35))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(array6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel41)
                                .addGap(18, 18, 18)
                                .addComponent(int10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(int1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel42)
                                .addGap(18, 18, 18)
                                .addComponent(int11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(int4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel45)
                                .addGap(18, 18, 18)
                                .addComponent(int14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(int2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel43)
                                .addGap(18, 18, 18)
                                .addComponent(int12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(int3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel44)
                                .addGap(18, 18, 18)
                                .addComponent(int13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(18, 18, 18)
                        .addComponent(array5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel40)
                        .addGap(18, 18, 18)
                        .addComponent(int9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(18, 18, 18)
                        .addComponent(array4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel39)
                        .addGap(18, 18, 18)
                        .addComponent(int8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(18, 18, 18)
                        .addComponent(array3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel38)
                        .addGap(18, 18, 18)
                        .addComponent(int7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(18, 18, 18)
                        .addComponent(array2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel37)
                        .addGap(18, 18, 18)
                        .addComponent(int6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addComponent(array1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel36)
                        .addGap(18, 18, 18)
                        .addComponent(int5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(array1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36)
                    .addComponent(int5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(array2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(int6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(array3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38)
                    .addComponent(int7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(array4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39)
                    .addComponent(int8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(array5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40)
                    .addComponent(int9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(array6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41)
                    .addComponent(int10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(int1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42)
                    .addComponent(int11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(int2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43)
                    .addComponent(int12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(int3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44)
                    .addComponent(int13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel45)
                        .addComponent(int14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel35)
                        .addComponent(int4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Unknown Definitions", jPanel5);

        jLabel46.setText("unknownInt15");

        int15.setText(""+defs.unknownInt15);

        jLabel47.setText("unknownInt16");

        int16.setText(""+defs.unknownInt16);

        jLabel48.setText("unknownInt17");

        int17.setText(""+defs.unknownInt17);

        jLabel49.setText("unknownInt18");

        int18.setText(""+defs.unknownInt18);

        jLabel50.setText("unknownInt19");

        int19.setText(""+defs.unknownInt19);

        jLabel51.setText("unknownInt20");

        int20.setText(""+defs.unknownInt20);

        jLabel52.setText("unknownInt21");

        int21.setText(""+defs.unknownInt21);

        jLabel53.setText("unknownInt22");

        int22.setText(""+defs.unknownInt22);

        jLabel54.setText("unknownInt23");

        int23.setText(""+defs.unknownInt23);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel46)
                        .addGap(18, 18, 18)
                        .addComponent(int15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel47)
                        .addGap(18, 18, 18)
                        .addComponent(int16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel48)
                        .addGap(18, 18, 18)
                        .addComponent(int17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel49)
                        .addGap(18, 18, 18)
                        .addComponent(int18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel50)
                        .addGap(18, 18, 18)
                        .addComponent(int19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel51)
                        .addGap(18, 18, 18)
                        .addComponent(int20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel52)
                        .addGap(18, 18, 18)
                        .addComponent(int21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel53)
                        .addGap(18, 18, 18)
                        .addComponent(int22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel54)
                        .addGap(18, 18, 18)
                        .addComponent(int23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(425, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(int15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(int16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(int17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(int18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(int19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(int20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(int21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel53)
                    .addComponent(int22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel54)
                    .addComponent(int23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Unknown Definitions(2)", jPanel6);

        clientScriptOutput.setColumns(20);
        clientScriptOutput.setRows(5);
        clientScriptOutput.setText(getClientScripts());
        jScrollPane1.setViewportView(clientScriptOutput);

        jLabel26.setText("KEY");

        jLabel55.setText("VALUE");

        jLabel56.setText("Add the keys to the left to the boxes to edit them.");

        jLabel57.setText("Add new keys in the boxes to give the item new clientscripts.");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel57)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(csk2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(csk1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(csk3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(csk4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(csk5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(csk6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(csk7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel26))
                            .addGap(58, 58, 58)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(csv1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(csv2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(csv3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(csv4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(csv5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(csv6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(csv7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel55)))
                        .addComponent(jLabel56)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(jLabel55))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(csk1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(csv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(csk2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(csv2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(csk3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(csv3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(csk4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(csv4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(csk5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(csv5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(csk6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(csv6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(csk7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(csv7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(jLabel56)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel57))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Clientscripts", jPanel7);

        currentViewLabel.setText("Currently Viewing Definitions of Item: "+defs.getId()+" - "+defs.getName());

        jMenu1.setText("File");

        reloadMenuBtn.setText("Reload");
        reloadMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadMenuBtnActionPerformed(evt);
            }
        });
        jMenu1.add(reloadMenuBtn);

        saveMenuBtn.setText("Save");
        saveMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuBtnActionPerformed(evt);
            }
        });
        jMenu1.add(saveMenuBtn);

        addModelMenuBtn.setText("Add Model");
        addModelMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addModelMenuBtnActionPerformed(evt);
            }
        });
        jMenu1.add(addModelMenuBtn);

        exportMenuBtn.setText("Export to .txt");
        exportMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportMenuBtnActionPerformed(evt);
            }
        });
        jMenu1.add(exportMenuBtn);

        exitMenuBtn.setText("Exit");
        exitMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuBtnActionPerformed(evt);
            }
        });
        jMenu1.add(exitMenuBtn);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(currentViewLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(currentViewLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitMenuBtnActionPerformed

    private void exportMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportMenuBtnActionPerformed
        export();
    }//GEN-LAST:event_exportMenuBtnActionPerformed

    private void addModelMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addModelMenuBtnActionPerformed
        addModel();
    }//GEN-LAST:event_addModelMenuBtnActionPerformed

    private void saveMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuBtnActionPerformed
        save();
    }//GEN-LAST:event_saveMenuBtnActionPerformed

    private void reloadMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadMenuBtnActionPerformed
        itemName.setText("" + defs.getName());
        value.setText("" + defs.getValue());
        membersOnly.setSelected(defs.isMembersObject());
        stackIDs.setText("" + getStackIDs());
        stackAmts.setText("" + getStackAmts());
        stackable.setText("" + defs.getStackable());
        invModelZoom.setText("" + defs.getSpriteScale());
        modelRot1.setText("" + defs.getSpritePitch());
        ModelRot2.setText("" + defs.getSpriteCameraRoll());
        ModelOffset1.setText("" + defs.getSpriteTranslateX());
        modelOffset2.setText("" + defs.getSpriteTranslateY());
        invModel.setText("" + defs.getModelId());
        maleEquip1.setText("" + defs.getPrimaryMaleModel());
        femaleEquip1.setText("" + defs.getPrimaryFemaleModel());
        maleEquip2.setText("" + defs.getSecondaryMaleModel());
        femaleEquip2.setText("" + defs.getSecondaryFemaleModel());
        maleEquip3.setText("" + defs.getTertiaryMaleEquipmentModel());
        femaleEquip3.setText("" + defs.getTertiaryFemaleEquipmentModel());
        invOptions.setText("" + getInventoryOpts());
        groundOptions.setText("" + getGroundOpts());
        modelColors.setText("" + getChangedModelColors());
        textureColors.setText("" + getChangedTextureColors());
        switchNote.setText("" + defs.certID);
        note.setText("" + defs.certTemplateID);
        shiftClickIndex.setText(""+defs.shiftClickIndex);
        searchable.setSelected(defs.isSearchable());
        int1.setText("" + defs.primaryMaleHeadPiece);
        int2.setText("" + defs.primaryFemaleHeadPiece);
        int3.setText("" + defs.secondaryMaleHeadPiece);
        int4.setText("" + defs.secondaryFemaleHeadPiece);
        int5.setText("" + defs.spriteCameraYaw);
        category.setText("" + defs.category);
        int7.setText("" + defs.groundScaleX);
        int8.setText("" + defs.groundScaleY);
        int9.setText("" + defs.groundScaleZ);
        int10.setText("" + defs.ambience);
        int11.setText("" + defs.diffusion);
        teamId.setText("" + defs.getTeam());
        unnotedId.setText("" + defs.unnotedId);
       notedId.setText(""+ defs.notedId);
        placeHolderId.setText(""+ defs.placeHolderId);
        placeHolderTemplateId.setText(""+defs.placeHolderTemplateId);
        clientScriptOutput.setText(getClientScripts());
    }//GEN-LAST:event_reloadMenuBtnActionPerformed

    private void export() {
        File f = new File(System.getProperty("user.home") + "/FrostyCacheEditor/items/");
        f.mkdirs();
        String lineSep = System.getProperty("line.separator");
        Writer writer = null;
        try {
            writer = new BufferedWriter(new OutputStreamWriter(
                    new FileOutputStream(System.getProperty("user.home") + "/FrostyCacheEditor/items/" + defs.id + ".txt"), "utf-8"));
            writer.write("name = " + defs.getName());
            writer.write(lineSep);
            writer.write("value = " + defs.getValue());
            writer.write(lineSep);
            writer.write("members only = " + String.valueOf(defs.isMembersObject()));
            writer.write(lineSep);
            writer.write("stack ids = " + getStackIDs());
            writer.write(lineSep);
            writer.write("stack amounts = " + getStackAmts());
            writer.write(lineSep);
            writer.write("stackable = " + defs.getStackable());
            writer.write(lineSep);
            writer.write("inv model zoom = " + defs.getSpriteScale());
            writer.write(lineSep);
            writer.write("model rotation 1 = " + defs.getSpritePitch());
            writer.write(lineSep);
            writer.write("model rotation 2 = " + defs.getSpriteCameraRoll());
            writer.write(lineSep);
            writer.write("model offset 1 = " + defs.getSpriteTranslateX());
            writer.write(lineSep);
            writer.write("model offset 2 = " + defs.getSpriteTranslateY());
            writer.write(lineSep);
            writer.write("inv model id = " + defs.getModelId());
            writer.write(lineSep);
            writer.write("male equip model id 1 = " + defs.getPrimaryMaleModel());
            writer.write(lineSep);
            writer.write("female equip model id 1 = " + defs.getPrimaryFemaleModel());
            writer.write(lineSep);
            writer.write("male equip model id 2 = " + defs.getSecondaryMaleModel());
            writer.write(lineSep);
            writer.write("female equip model id 2 = " + defs.getSecondaryFemaleModel());
            writer.write(lineSep);
            writer.write("male equip model id 3 = " + defs.getTertiaryMaleEquipmentModel());
            writer.write(lineSep);
            writer.write("female equip model id 3 = " + defs.getTertiaryFemaleEquipmentModel());
            writer.write(lineSep);
            writer.write("inventory options = " + getInventoryOpts());
            writer.write(lineSep);
            writer.write("ground options = " + getGroundOpts());
            writer.write(lineSep);
            writer.write("changed model colors = " + getChangedModelColors());
            writer.write(lineSep);
            writer.write("changed texture colors = " + getChangedTextureColors());
            writer.write(lineSep);
            writer.write("shiftClickIndex = " + defs.shiftClickIndex);
            writer.write(lineSep);
            writer.write("searchable = " + defs.searchable);
            writer.write(lineSep);
            writer.write("noted item id = " + defs.certTemplateID);
            writer.write(lineSep);
            writer.write("tertiaryMaleEquipmentModel = " + defs.tertiaryMaleEquipmentModel);
            writer.write(lineSep);
            writer.write("tertiaryFemaleEquipmentModel = " + defs.tertiaryFemaleEquipmentModel);
            writer.write(lineSep);
            writer.write("primaryMaleHeadPiece = " + defs.primaryMaleHeadPiece);
            writer.write(lineSep);
            writer.write("primaryFemaleHeadPiece = " + defs.primaryFemaleHeadPiece);
            writer.write(lineSep);
            writer.write("primaryFemaleHeadPiece = " + defs.secondaryMaleHeadPiece);
            writer.write(lineSep);
            writer.write("secondaryFemaleHeadPiece = " + defs.secondaryFemaleHeadPiece);
            writer.write(lineSep);
            writer.write("spriteCameraYaw = " + defs.spriteCameraYaw);
            writer.write(lineSep);
            writer.write("category = "+ defs.category);
            writer.write(lineSep);
            writer.write("groundScaleX = " + defs.groundScaleX);
            writer.write(lineSep);
            writer.write("groundScaleY = " + defs.groundScaleY);
            writer.write(lineSep);
            writer.write("groundScaleZ = " + defs.groundScaleZ);
            writer.write(lineSep);
            writer.write("ambience = " + defs.ambience);
            writer.write(lineSep);
            writer.write("diffusion = " + defs.diffusion);
            writer.write(lineSep);
            writer.write("team = "+ defs.team);
            writer.write(lineSep);
            writer.write("unnotedId = "+ defs.unnotedId);
            writer.write(lineSep);
            writer.write("notedId = "+ defs.notedId);
            writer.write(lineSep);
            writer.write("placeHolderId = "+ defs.placeHolderId);
            writer.write(lineSep);
            writer.write("placeHolderTemplateId = "+ defs.placeHolderTemplateId);
            writer.write(lineSep);

            writer.write("params");
            writer.write(lineSep);
            if (defs.params != null) {
                for (int key : defs.params.keySet()) {
                    Object value = defs.params.get(key);
                    writer.write("KEY: " + key + ", VALUE: " + value);
                    writer.write(lineSep);
                }
            }
        } catch (IOException ex) {
            Main.log("ItemEditor", "Failed to export Item Defs to .txt");
        } finally {
            try {
                writer.close();
            } catch (Exception ex) {
            }
        }
    }

    private void save() {
        try {
            defs.setName(itemName.getText().toString());
            defs.setValue(Integer.parseInt(value.getText().toString()));
            defs.setMembersObject(membersOnly.isSelected());
            if (!stackIDs.getText().equals("")) {
                String[] stackIds = stackIDs.getText().split(";");
                for (int i = 0; i < defs.getStackIDs().length; i++) {
                    defs.getStackIDs()[i] = Integer.parseInt(stackIds[i]);
                }
            }
            if (!stackAmts.getText().equals("")) {
                String[] stackAmounts = stackAmts.getText().split(";");
                for (int i = 0; i < defs.getStackAmounts().length; i++) {
                    defs.getStackAmounts()[i] = Integer.parseInt(stackAmounts[i]);
                }
            }
            defs.setStackable(Integer.parseInt(stackable.getText().toString()));
            defs.setSpriteScale(Integer.parseInt(invModelZoom.getText().toString()));
            defs.setSpritePitch(Integer.parseInt(modelRot1.getText().toString()));
            defs.setSpriteCameraRoll(Integer.parseInt(ModelRot2.getText().toString()));
            defs.setSpriteTranslateX(Integer.parseInt(ModelOffset1.getText().toString()));
            defs.setSpriteTranslateY(Integer.parseInt(modelOffset2.getText().toString()));
            defs.setModelId(Integer.parseInt(invModel.getText().toString()));
            defs.primaryMaleModel = Integer.parseInt(maleEquip1.getText().toString());
            defs.secondaryMaleModel = Integer.parseInt(maleEquip2.getText().toString());
            defs.tertiaryMaleEquipmentModel = Integer.parseInt(maleEquip3.getText().toString());
            defs.primaryFemaleModel = Integer.parseInt(femaleEquip1.getText().toString());
            defs.secondaryFemaleModel = Integer.parseInt(femaleEquip2.getText().toString());
            defs.tertiaryFemaleEquipmentModel = Integer.parseInt(femaleEquip3.getText().toString());
            String[] groundOpts = groundOptions.getText().split(";");
            for (int i = 0; i < defs.getGroundActions().length; i++) {
                defs.getGroundActions()[i] = groundOpts[i].equals("null") ? null : groundOpts[i];
            }
            String[] invOpts = invOptions.getText().split(";");
            for (int i = 0; i < defs.getItemActions().length; i++) {
                defs.getItemActions()[i] = invOpts[i].equals("null") ? null : invOpts[i];
            }
            defs.resetModelColors();
            if (!modelColors.getText().equals("")) {
                String[] splitedModelColorsTexts = modelColors.getText().split(";");
                for (String t : splitedModelColorsTexts) {
                    String[] editedColor = t.split("=");
                    defs.changeModelColor(Integer.valueOf(editedColor[0]), Integer.valueOf(editedColor[1]));
                }
            }
            defs.resetTextureColors();
            if (!textureColors.getText().equals("")) {
                String[] splitedTextureColorsTexts = textureColors.getText().split(";");
                for (String t : splitedTextureColorsTexts) {
                    String[] editedColor = t.split("=");
                    defs.changeTextureColor(Integer.valueOf(editedColor[0]), Integer.valueOf(editedColor[1]));
                }
            }
            defs.shiftClickIndex = Integer.parseInt(shiftClickIndex.getText());
            defs.searchable = Boolean.parseBoolean(searchable.getText());
            defs.primaryMaleHeadPiece = Integer.parseInt(int1.getText());
            defs.primaryFemaleHeadPiece = Integer.parseInt(int2.getText());
            defs.secondaryMaleHeadPiece = Integer.parseInt(int3.getText());
            defs.secondaryFemaleHeadPiece = Integer.parseInt(int4.getText());
            defs.spriteCameraYaw = Integer.parseInt(int5.getText());
            defs.category = Integer.parseInt(category.getText());
            defs.groundScaleX = Integer.parseInt(int7.getText());
            defs.groundScaleY = Integer.parseInt(int8.getText());
            defs.groundScaleZ = Integer.parseInt(int9.getText());
            defs.ambience = Integer.parseInt(int10.getText());
            defs.diffusion = Integer.parseInt(int11.getText());
            defs.setTeam(Integer.parseInt(teamId.getText().toString()));
            defs.unnotedId = Integer.parseInt(unnotedId.getText());
            defs.notedId = Integer.parseInt(notedId.getText());
            defs.placeHolderId = Integer.parseInt(placeHolderId.getText());
            defs.placeHolderTemplateId = Integer.parseInt(placeHolderTemplateId.getText());
            // defs.aString7902 = String.parseString(itemName.getText().toString());
            try {
                if (!csk1.getText().equals("") && !csv1.getText().equals("")) {
                    try {
                        defs.params.remove(csk1);
                        defs.params.put(Integer.parseInt(csk1.getText()), Integer.parseInt(csv1.getText()));
                    } catch (Exception e) {
                        defs.params.remove(csk1);
                        defs.params.put(Integer.parseInt(csk1.getText()), csv1.getText().toString());
                    }
                }
                if (!csk2.getText().equals("") && !csv2.getText().equals("")) {
                    try {
                        defs.params.remove(csk2);
                        defs.params.put(Integer.parseInt(csk2.getText()), Integer.parseInt(csv2.getText()));
                    } catch (Exception e) {
                        defs.params.remove(csk2);
                        defs.params.put(Integer.parseInt(csk2.getText()), csv2.getText().toString());
                    }
                }
                if (!csk3.getText().equals("") && !csv3.getText().equals("")) {
                    try {
                        defs.params.remove(csk3);
                        defs.params.put(Integer.parseInt(csk3.getText()), Integer.parseInt(csv3.getText()));
                    } catch (Exception e) {
                        defs.params.remove(csk3);
                        defs.params.put(Integer.parseInt(csk3.getText()), csv3.getText().toString());
                    }
                }
                if (!csk4.getText().equals("") && !csv4.getText().equals("")) {
                    try {
                        defs.params.remove(csk4);
                        defs.params.put(Integer.parseInt(csk4.getText()), Integer.parseInt(csv4.getText()));
                    } catch (Exception e) {
                        defs.params.remove(csk4);
                        defs.params.put(Integer.parseInt(csk4.getText()), csv4.getText().toString());
                    }
                }
                if (!csk5.getText().equals("") && !csv5.getText().equals("")) {
                    try {
                        defs.params.remove(csk5);
                        defs.params.put(Integer.parseInt(csk5.getText()), Integer.parseInt(csv5.getText()));
                    } catch (Exception e) {
                        defs.params.remove(csk5);
                        defs.params.put(Integer.parseInt(csk5.getText()), csv5.getText().toString());
                    }
                }
                if (!csk6.getText().equals("") && !csv6.getText().equals("")) {
                    try {
                        defs.params.remove(csk6);
                        defs.params.put(Integer.parseInt(csk6.getText()), Integer.parseInt(csv6.getText()));
                    } catch (Exception e) {
                        defs.params.remove(csk6);
                        defs.params.put(Integer.parseInt(csk6.getText()), csv6.getText().toString());
                    }
                }
                if (!csk7.getText().equals("") && !csv7.getText().equals("")) {
                    try {
                        defs.params.remove(csk7);
                        defs.params.put(Integer.parseInt(csk7.getText()), Integer.parseInt(csv7.getText()));
                    } catch (Exception e) {
                        defs.params.remove(csk7);
                        defs.params.put(Integer.parseInt(csk7.getText()), csv7.getText().toString());
                    }
                }
            } catch (Exception e) {
                defs.params = new HashMap<Integer, Object>(1);
            }
            defs.write(is.STORE);
            is.updateItemDefs(defs);
        } catch (Exception e) {
            Main.log("ItemEditor", "Cannot save. Please check for mistypes.");
        }
    }

    private void addModel() {
        JFrame frame = new JFrame();
        int result = JOptionPane.showConfirmDialog(frame, "Do you want to specify a model ID?");
        if (result == JOptionPane.YES_OPTION) {
            JFrame newModel = new JFrame();
            Object newModelResult = JOptionPane.showInputDialog(newModel, "Enter new model ID:");
            if (Integer.parseInt(newModelResult.toString()) != -1) {
                final JFileChooser fc = new JFileChooser();
                fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
                int returnVal = fc.showOpenDialog(ItemEditor.this);

                if (returnVal == JFileChooser.APPROVE_OPTION) {
                    File file = fc.getSelectedFile();
                    try {
                        Main.log("ItemEditor", "The model ID of the recently packed model is: " + Utils.packCustomModel(is.STORE, Utils.getBytesFromFile(new File(file.getPath().toString())), Integer.parseInt(newModelResult.toString())));
                    } catch (IOException ex) {
                        Main.log("ItemEditor", "There was an error packing the model.");
                    }
                }
            }
        } else if (result == JOptionPane.NO_OPTION) {
            final JFileChooser fc = new JFileChooser();
            fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
            int returnVal = fc.showOpenDialog(ItemEditor.this);

            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
                try {
                    Main.log("ItemEditor", "The model ID of the recently packed model is: " + Utils.packCustomModel(is.STORE, Utils.getBytesFromFile(new File(file.getPath().toString()))));
                } catch (IOException ex) {
                    Main.log("ItemEditor", "There was an error packing the model.");
                }
            }
        }

    }

    public String getInventoryOpts() {
        String text = "";
        for (String option : defs.getItemActions()) {
            text += (option == null ? "null" : option) + ";";
        }
        return text;
    }

    public String getGroundOpts() {
        String text = "";
        for (String option : defs.getGroundActions()) {
            text += (option == null ? "null" : option) + ";";
        }
        return text;
    }

    public String getChangedModelColors() {
        String text = "";
        if (defs.originalModelColors != null) {
            for (int i = 0; i < defs.originalModelColors.length; i++) {
                text += defs.originalModelColors[i] + "=" + defs.modifiedModelColors[i] + ";";
            }
        }
        return text;
    }

    public String getChangedTextureColors() {
        String text = "";
        if (defs.originalTextureColors != null) {
            for (int i = 0; i < defs.originalTextureColors.length; i++) {
                text += defs.originalTextureColors[i] + "=" + defs.modifiedTextureColors[i] + ";";
            }
        }
        return text;
    }

    public String getStackIDs() {
        String text = "";
        try {
            for (int index : defs.getStackIDs()) {
                text += index + ";";
            }
        } catch (Exception e) {
        }
        return text;
    }

    public String getClientScripts() {
        String text = "";
        String lineSep = System.getProperty("line.separator");
        if (defs.params != null) {
            for (int key : defs.params.keySet()) {
                Object value = defs.params.get(key);
                text += "KEY: " + key + ", VALUE: " + value;
                text += lineSep;
            }
        }
        return text;
    }

    public String getStackAmts() {
        String text = "";
        try {
            for (int index : defs.getStackAmounts()) {
                text += index + ";";
            }
        } catch (Exception e) {
        }
        return text;
    }

    public String getUnknownArray1() {
        String text = "";
        try {
            for (int index : defs.unknownArray1) {
                text += index + ";";
            }
        } catch (Exception e) {
        }
        return text;
    }

    public String getUnknownArray2() {
        String text = "";
        try {
            for (int index : defs.unknownArray2) {
                text += index + ";";
            }
        } catch (Exception e) {
        }
        return text;
    }

    public String getUnknownArray3() {
        String text = "";
        try {
            for (int index : defs.unknownArray3) {
                text += index + ";";
            }
        } catch (Exception e) {
        }
        return text;
    }

    public String getUnknownArray4() {
        String text = "";
        try {
            for (int index : defs.unknownArray4) {
                text += index + ";";
            }
        } catch (Exception e) {
        }
        return text;
    }

    public String getUnknownArray5() {
        String text = "";
        try {
            for (int index : defs.unknownArray5) {
                text += index + ";";
            }
        } catch (Exception e) {
        }
        return text;
    }

    public String getUnknownArray6() {
        String text = "";
        try {
            for (int index : defs.unknownArray6) {
                text += index + ";";
            }
        } catch (Exception e) {
        }
        return text;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ModelOffset1;
    private javax.swing.JTextField ModelRot2;
    private javax.swing.JMenuItem addModelMenuBtn;
    private javax.swing.JTextField array1;
    private javax.swing.JTextField array2;
    private javax.swing.JTextField array3;
    private javax.swing.JTextField array4;
    private javax.swing.JTextField array5;
    private javax.swing.JTextField array6;
    private javax.swing.JTextArea clientScriptOutput;
    private javax.swing.JTextField csk1;
    private javax.swing.JTextField csk2;
    private javax.swing.JTextField csk3;
    private javax.swing.JTextField csk4;
    private javax.swing.JTextField csk5;
    private javax.swing.JTextField csk6;
    private javax.swing.JTextField csk7;
    private javax.swing.JTextField csv1;
    private javax.swing.JTextField csv2;
    private javax.swing.JTextField csv3;
    private javax.swing.JTextField csv4;
    private javax.swing.JTextField csv5;
    private javax.swing.JTextField csv6;
    private javax.swing.JTextField csv7;
    private javax.swing.JLabel currentViewLabel;
    private javax.swing.JTextField equipSlot;
    private javax.swing.JTextField equipType;
    private javax.swing.JMenuItem exitMenuBtn;
    private javax.swing.JMenuItem exportMenuBtn;
    private javax.swing.JTextField femaleEquip1;
    private javax.swing.JTextField femaleEquip2;
    private javax.swing.JTextField femaleEquip3;
    private javax.swing.JTextField groundOptions;
    private javax.swing.JTextField int1;
    private javax.swing.JTextField int10;
    private javax.swing.JTextField int11;
    private javax.swing.JTextField int12;
    private javax.swing.JTextField int13;
    private javax.swing.JTextField int14;
    private javax.swing.JTextField int15;
    private javax.swing.JTextField int16;
    private javax.swing.JTextField int17;
    private javax.swing.JTextField int18;
    private javax.swing.JTextField int19;
    private javax.swing.JTextField int2;
    private javax.swing.JTextField int20;
    private javax.swing.JTextField int21;
    private javax.swing.JTextField int22;
    private javax.swing.JTextField int23;
    private javax.swing.JTextField int24;
    private javax.swing.JTextField int25;
    private javax.swing.JTextField int26;
    private javax.swing.JTextField int27;
    private javax.swing.JTextField int28;
    private javax.swing.JTextField int29;
    private javax.swing.JTextField int30;
    private javax.swing.JTextField int3;
    private javax.swing.JTextField int4;
    private javax.swing.JTextField int5;
    private javax.swing.JTextField int6;
    private javax.swing.JTextField int7;
    private javax.swing.JTextField int8;
    private javax.swing.JTextField int9;
    private javax.swing.JTextField invModel;
    private javax.swing.JTextField invModelZoom;
    private javax.swing.JTextField invOptions;
    private javax.swing.JTextField itemName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lend;
    private javax.swing.JTextField maleEquip1;
    private javax.swing.JTextField maleEquip2;
    private javax.swing.JTextField maleEquip3;
    private javax.swing.JCheckBox membersOnly;
    private javax.swing.JTextField modelColors;
    private javax.swing.JTextField modelOffset2;
    private javax.swing.JTextField modelRot1;
    private javax.swing.JTextField note;
    private javax.swing.JMenuItem reloadMenuBtn;
    private javax.swing.JMenuItem saveMenuBtn;
    private javax.swing.JTextField stackAmts;
    private javax.swing.JTextField stackIDs;
    private javax.swing.JTextField stackable;
    private javax.swing.JTextField switchLend;
    private javax.swing.JTextField switchNote;
    private javax.swing.JTextField teamId;
    private javax.swing.JTextField textureColors;
    private javax.swing.JCheckBox searchable;
    private javax.swing.JTextField value;
    // End of variables declaration//GEN-END:variables
}
